### ISSUE TITLE
Feature possiblity: add stdout option to analyzerMode

### ISSUE THREAD

**Issue by Jogai** [nonzzz/vite-bundle-analyzer#10]
Not sure if you're open to requests, but I'm mainly looking for a decent summary of the build output in the terminal. This makes most sense on a build server as well because the final build does not need to have a fancy result. Something like the following is more than enough: `16 chunks of 876 kB (parsed: 432 kB | gzipped: 123 kB)`

**Comment by nonzzz** [comment]
Looks well but I would like to know what is the format of output to stdout?

**Comment by a3mitskevich** [comment]
Hello! 👋 I'm not sure, but are you requesting a summary log for the serve process or the build? If it's for the serve process, it doesn't make sense right now because Vite generates chunks that are not similar for both processes. If it's for the build, I believe this request should be redirected to the Vite repository because it exhibits a similar behavior out of the box

**Comment by Jogai** [comment]
For the build. You triggered me to think about the build, and I found [doesdev/rollup-plugin-analyzer](https://github.com/doesdev/rollup-plugin-analyzer) that works for me. 

Rollup plugins for inspiration: 
 - https://github.com/oscarmarina/rollup-plugin-total-bundlesize (close to my request)
 - https://github.com/yousifalraheem/rollup-plugin-summary

**Comment by a3mitskevich** [comment]
I apologize for any confusion. I still don't understand why you are hesitant to open an issue in the Vite repository. By default, Vite already provides information about every generated chunk, and it would be beneficial to enhance it with the option to view summary information.

![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/77048647/cfdf5f49-2815-4dae-871b-1de15f5704d7)

It will be working more nativity and have a more strongest support instead of third-party plugins

**Comment by nonzzz** [comment]
off topic if only generate a simple dependencies tree to stdout i think it's interesting feature.

**Comment by Jogai** [comment]
@a3mitskevich Its handled by rollup so they will tell me to take it up with them or to make a plugin. I feel this plugin is there for 98% already.

**Comment by a3mitskevich** [comment]
Alright, no objections from my side. I'm simply sharing my thoughts.

**Comment by a3mitskevich** [comment]
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/77048647/92565e9e-efde-4684-9566-ee2f6863798a)
@Jogai @nonzzz Intermediate result. If it's okay, I will proceed to open a pull request.

**Comment by nonzzz** [comment]
`0.6.0` has been released enjoy it.

**Comment by Jogai** [comment]
Awesome, thanks!
